<?php

/**
 * @package     Optimiseweb_Banners
 * @author      Kathir Vel (vkathirvel@gmail.com)
 * @copyright   Copyright (c) 2015 Kathir Vel
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
if ($this->getIdentifier() != NULL) {
    switch ($this->getBannerType()) {
        case 'genericdiv':
            echo $this->getGenericDivHtml($this->getIdentifier(), $this->getContainerId(), $this->getContainerClass(), $this->getItemClass(), $this->getImageClass(), $this->getLinkClass(), $this->getImageLinkContainerClass(), $this->getHeadingClass(), $this->getContentClass());
            break;
        case 'slidejs':
            echo $this->getSlideJsHtml($this->getIdentifier(), $this->getContainerId(), $this->getContainerClass());
            break;
        case 'jcarousel':
            echo $this->getJcarouselHtml($this->getIdentifier(), $this->getContainerId(), $this->getContainerClass(), $this->getLiClass());
            break;
        case 'flexslider':
            echo $this->getFlexSliderHtml($this->getIdentifier(), $this->getContainerClass());
            break;
        case 'bxslider':
            echo $this->getBxSliderHtml($this->getIdentifier(), $this->getSliderClass(), $this->getContainerClass());
            break;
        default:
            break;
    }
}